spring:
  application:
    name: genai-chatbot
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/chatbotdb}
    username: ${SPRING_DATASOURCE_USERNAME:chatbotuser}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  ai:
    openai:
      enable: false
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_API_BASE_URL:https://api.openai.com/v1}

logging:
  level:
    root: INFO
    com.shubhajit.genai.chatbot: DEBUG
  file:
    name: logs/genai-chatbot.log
