#debug: true
spring:
  application:
    name: genai-chatbot
  ai:
    ollama:
      chat:
        options:
          model: mistral
      base-url: http://localhost:11434

logging:
  level:
    root: INFO
    com:
      shubhajit:
        genai:
          chatbot: DEBUG
    org:
      springframework:
        web: DEBUG # Enable only in development
  file:
    name: logs/genai-chatbot.log
